// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GGServices
{
        public const string achievement_amateur_locksmith = "CgkI2-rT87cREAIQBg"; // <GPGSID>
        public const string achievement_intermediate_locksmith = "CgkI2-rT87cREAIQBw"; // <GPGSID>
        public const string achievement_silver_key = "CgkI2-rT87cREAIQBA"; // <GPGSID>
        public const string achievement_professional_lock_cracker = "CgkI2-rT87cREAIQCA"; // <GPGSID>
        public const string achievement_bronze_key = "CgkI2-rT87cREAIQAg"; // <GPGSID>
        public const string leaderboard_unlocked_leaderboard = "CgkI2-rT87cREAIQAA"; // <GPGSID>
        public const string achievement_golden_key = "CgkI2-rT87cREAIQBQ"; // <GPGSID>

}

